In [7]:
import torch
print(torch.__version__)

# Scalar tensor
scalar_tensor = torch.tensor(7)
print(f"Scalar value: {scalar_tensor}")

# Get the dimension of the scalar tensor
scalar_tensor_dim = scalar_tensor.ndim
print(f"Scalar dimension: {scalar_tensor_dim}")

# Get the scalar value as a Python number
scalar_value = scalar_tensor.item()
print(f"Scalar item: {scalar_value}")

2.4.0+cu121
Scalar value: 7
Scalar dimension: 0
Scalar item: 7


In [8]:
# Vector tensor
vector_tensor = torch.tensor([7, 7])
print(f"Vector value: {vector_tensor}")

# Get the dimension of the vector tensor
vector_tensor_dim = vector_tensor.ndim
print(f"Vector dimension: {vector_tensor_dim}")

# Get the shape of the vector tensor
vector_tensor_shape = vector_tensor.shape
print(f"Vector shape: {vector_tensor_shape}")

Vector value: tensor([7, 7])
Vector dimension: 1
Vector shape: torch.Size([2])


In [9]:
# Matrix tensor
matrix_tensor = torch.tensor([[7, 7], [8, 8]])
print(f"Matrix value: \n{matrix_tensor}")

# Get the dimension of the matrix tensor
matrix_tensor_dim = matrix_tensor.ndim
print(f"Matrix dimension: {matrix_tensor_dim}")

# Get the shape of the matrix tensor
matrix_tensor_shape = matrix_tensor.shape
print(f"Matrix shape: {matrix_tensor_shape}")

Matrix value: 
tensor([[7, 7],
        [8, 8]])
Matrix dimension: 2
Matrix shape: torch.Size([2, 2])


In [10]:
# 3D Tensor
tensor_3d = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(f"3D Tensor value: \n{tensor_3d}")

# Get the dimension of the 3D tensor
tensor_3d_dim = tensor_3d.ndim
print(f"3D Tensor dimension: {tensor_3d_dim}")

# Get the shape of the 3D tensor
tensor_3d_shape = tensor_3d.shape
print(f"3D Tensor shape: {tensor_3d_shape}")

3D Tensor value: 
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
3D Tensor dimension: 3
3D Tensor shape: torch.Size([1, 3, 3])


In [11]:
# Create a random tensor of size (1, 3, 4)
random_tensor = torch.rand(size=(1, 3, 4))
print(f"Random tensor value: \n{random_tensor}")

# Create a tensor filled with zeros of size (3, 4)
zeros_tensor = torch.zeros(size=(3, 4))
print(f"Zeros tensor value: \n{zeros_tensor}")

# Create a tensor filled with ones of size (3, 4)
ones_tensor = torch.ones(size=(3, 4))
print(f"Ones tensor value: \n{ones_tensor}")

# Create a tensor with a range of values from 0 to 100 with a step of 10
range_tensor = torch.arange(start=0, end=100, step=10)
print(f"Range tensor value: {range_tensor}")

# Create a tensor of zeros with the same shape as another tensor
zeros_like_tensor = torch.zeros_like(input=range_tensor)
print(f"Tensor with zeros like range_tensor: {zeros_like_tensor}")

Random tensor value: 
tensor([[[0.0483, 0.1169, 0.7534, 0.4898],
         [0.2083, 0.3300, 0.8267, 0.5876],
         [0.9432, 0.6863, 0.5963, 0.0380]]])
Zeros tensor value: 
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
Ones tensor value: 
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
Range tensor value: tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Tensor with zeros like range_tensor: tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
