In [1]:
import torch

# Convert a tensor to a different data type (float32 to float16)
float32_tensor = torch.tensor([1.0, 2.0, 3.0])  # Example tensor
float16_tensor = float32_tensor.type(torch.float16)
print(float16_tensor)

tensor([1., 2., 3.], dtype=torch.float16)


In [2]:
# Basic tensor operations: addition, subtraction, multiplication, division
basic_tensor = torch.tensor([1, 2, 3])

print(basic_tensor + 10)  # Add 10 to each element
print(basic_tensor - 10)  # Subtract 10 from each element
print(basic_tensor * 10)  # Multiply each element by 10
print(basic_tensor / 10)  # Divide each element by 10

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])


In [3]:
# Element-wise multiplication
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([1, 2, 3])
print(tensor1 * tensor2)  # Each element in tensor1 is multiplied by the corresponding element in tensor2

# Dot product (matrix multiplication)
dot_product_result = torch.matmul(tensor1, tensor2)
print(dot_product_result)

# Rules for matrix multiplication:
# 1. The inner dimensions must match (e.g., (2, 3) @ (3, 2) works, but (3, 2) @ (3, 2) does not).
# 2. The resulting matrix has the shape of the outer dimensions (e.g., (2, 3) @ (3, 2) -> (2, 2)).

tensor([1, 4, 9])
tensor(14)


In [4]:
# Example of incorrect matrix multiplication
matrix_A = torch.tensor([[1, 2], [3, 4], [5, 6]])  # Shape: (3, 2)
matrix_B = torch.tensor([[7, 10], [8, 11], [9, 12]])  # Shape: (3, 2)

print(matrix_A.shape)  # Output: (3, 2)
print(matrix_B.shape)  # Output: (3, 2)

# Incorrect matrix multiplication (shapes do not align)
# print(torch.matmul(matrix_A, matrix_B))  # Uncommenting this will raise a RuntimeError

# Fix the issue by transposing matrix_B
matrix_B_transposed = matrix_B.T
print(matrix_B_transposed)  # Transposed matrix_B
print(matrix_B_transposed.shape)  # New shape: (2, 3)

# Now, matrix multiplication works
correct_matrix_mult = torch.matmul(matrix_A, matrix_B_transposed)
print(correct_matrix_mult)

torch.Size([3, 2])
torch.Size([3, 2])
tensor([[ 7,  8,  9],
        [10, 11, 12]])
torch.Size([2, 3])
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [5]:
# Basic tensor operations: min, max, sum, mean
range_tensor = torch.arange(0, 100, 10)
print(range_tensor)

print(range_tensor.min())  # Minimum value in the tensor
print(range_tensor.max())  # Maximum value in the tensor
print(range_tensor.sum())  # Sum of all elements in the tensor
print(range_tensor.type(torch.float32).mean())  # Mean of elements, requires float32 type

# Find the index of the minimum and maximum values
print(range_tensor.argmin())  # Index of the minimum value
print(range_tensor.argmax())  # Index of the maximum value

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
tensor(0)
tensor(90)
tensor(450)
tensor(45.)
tensor(0)
tensor(9)
