In [13]:
import torch

# Creating a tensor
tensor_A = torch.arange(1., 10.)
print(f"Original tensor: {tensor_A}")
print(f"Original shape: {tensor_A.shape}")

# Reshaping the tensor (changes the shape)
tensor_reshaped = tensor_A.reshape(9, 1)
print(f"Reshaped tensor:\n{tensor_reshaped}")
print(f"Reshaped shape: {tensor_reshaped.shape}")

Original tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Original shape: torch.Size([9])
Reshaped tensor:
tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Reshaped shape: torch.Size([9, 1])


In [14]:
# Changing the view (similar to reshape but shares the same data)
tensor_view = tensor_A.view(1, 9)
print(f"Viewed tensor:\n{tensor_view}")
print(f"Viewed shape: {tensor_view.shape}")

# Stacking tensors (combining multiple tensors along a specified dimension)
tensor_stacked = torch.stack([tensor_A, tensor_A, tensor_A], dim=1)
print(f"Stacked tensor:\n{tensor_stacked}")
print(f"Stacked shape: {tensor_stacked.shape}")

Viewed tensor:
tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Viewed shape: torch.Size([1, 9])
Stacked tensor:
tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.],
        [5., 5., 5.],
        [6., 6., 6.],
        [7., 7., 7.],
        [8., 8., 8.],
        [9., 9., 9.]])
Stacked shape: torch.Size([9, 3])


In [9]:
# Squeezing (removes all dimensions of size 1)
tensor_single_dim = tensor_A.reshape(1, 9)
print(f"Tensor before squeeze:\n{tensor_single_dim}")
print(f"Shape before squeeze: {tensor_single_dim.shape}")

tensor_squeezed = tensor_single_dim.squeeze()
print(f"Squeezed tensor:\n{tensor_squeezed}")
print(f"Shape after squeeze: {tensor_squeezed.shape}")

Tensor before squeeze:
tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Shape before squeeze: torch.Size([1, 9])
Squeezed tensor:
tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Shape after squeeze: torch.Size([9])


In [10]:
# Unsqueezing (adds a dimension of size 1 at the specified position)
tensor_unsqueezed = tensor_A.unsqueeze(0)  # Add a dimension at index 0
print(f"Unsqueezed tensor:\n{tensor_unsqueezed}")
print(f"Shape after unsqueeze: {tensor_unsqueezed.shape}")

# Permute (rearranges the dimensions of a tensor)
tensor_original = torch.rand(size=(224, 222, 3))  # Shape: [height, width, color_channels]
tensor_permuted = tensor_original.permute(2, 0, 1)  # Rearrange to [color_channels, height, width]
print(f"Permuted tensor:\n{tensor_permuted}")
print(f"Permuted shape: {tensor_permuted.shape}")

Unsqueezed tensor:
tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Shape after unsqueeze: torch.Size([1, 9])
Permuted tensor:
tensor([[[0.8219, 0.9992, 0.2425,  ..., 0.4471, 0.9324, 0.2879],
         [0.2032, 0.9071, 0.1590,  ..., 0.0763, 0.5737, 0.5609],
         [0.7700, 0.5847, 0.9996,  ..., 0.5394, 0.1786, 0.6417],
         ...,
         [0.4389, 0.8371, 0.7964,  ..., 0.5268, 0.5852, 0.6822],
         [0.1582, 0.3151, 0.7655,  ..., 0.9614, 0.0455, 0.2345],
         [0.2120, 0.3601, 0.4860,  ..., 0.5116, 0.3985, 0.0671]],

        [[0.5401, 0.0657, 0.7237,  ..., 0.7401, 0.0913, 0.3888],
         [0.1667, 0.9073, 0.7399,  ..., 0.9194, 0.6973, 0.1076],
         [0.4637, 0.8216, 0.3684,  ..., 0.4305, 0.1750, 0.3127],
         ...,
         [0.7901, 0.3894, 0.4612,  ..., 0.1588, 0.4838, 0.3723],
         [0.2001, 0.9127, 0.8390,  ..., 0.2781, 0.3622, 0.4769],
         [0.4140, 0.7443, 0.7263,  ..., 0.2838, 0.0247, 0.4614]],

        [[0.1825, 0.4778, 0.2163,  ..., 0.5673, 0.0017, 0.0668]