In [10]:
import torch
import numpy as np

# Torch tensor indexing and reshaping example
# Create a 1x3x3 tensor with values ranging from 1 to 9
x = torch.arange(1, 10).reshape(1, 3, 3)
print(f"Tensor x:\n{x}\nShape of x: {x.shape}\n")

# Accessing elements using different indexing methods
print(f"x[0]:\n{x[0]}\n")       # First 2D slice
print(f"x[0][0]:\n{x[0][0]}\n") # First row of the first slice
print(f"x[0][0][0]: {x[0][0][0]}\n") # First element of the first row of the first slice

Tensor x:
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Shape of x: torch.Size([1, 3, 3])

x[0]:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

x[0][0]:
tensor([1, 2, 3])

x[0][0][0]: 1



In [11]:
# Alternative indexing (equivalent to above)
print(f"x[0]:\n{x[0]}\n")       # First 2D slice (same as above)
print(f"x[0, 0]:\n{x[0, 0]}\n") # First row of the first slice (same as above)
print(f"x[0, 0, 0]: {x[0, 0, 0]}\n") # First element (same as above)

# NumPy array to PyTorch tensor conversion
array = np.arange(1.0, 8.0)  # Create a NumPy array from 1 to 7
tensor_from_numpy = torch.from_numpy(array)  # Convert NumPy array to PyTorch tensor
print(f"NumPy array:\n{array}")
print(f"Converted PyTorch tensor:\n{tensor_from_numpy}\n")

x[0]:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

x[0, 0]:
tensor([1, 2, 3])

x[0, 0, 0]: 1

NumPy array:
[1. 2. 3. 4. 5. 6. 7.]
Converted PyTorch tensor:
tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)



In [8]:
# Demonstrating reproducibility with random numbers in PyTorch
# Generating random tensors without manual seed
random_tensor_A = torch.rand(3, 3)
random_tensor_B = torch.rand(3, 3)
print(f"Random Tensor A:\n{random_tensor_A}")
print(f"Random Tensor B:\n{random_tensor_B}\n")

# Setting a random seed for reproducibility
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 3)
print(f"Random Tensor C (with seed {RANDOM_SEED}):\n{random_tensor_C}\n")

# Resetting the manual seed to get the same random values
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 3)
print(f"Random Tensor D (with seed {RANDOM_SEED}):\n{random_tensor_D}\n")

# Verify that the two tensors are identical
print(f"Are Tensor C and Tensor D identical? {random_tensor_C.equal(random_tensor_D)}\n")

Random Tensor A:
tensor([[0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])
Random Tensor B:
tensor([[0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317],
        [0.1053, 0.2695, 0.3588]])

Random Tensor C (with seed 42):
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])

Random Tensor D (with seed 42):
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])

Are Tensor C and Tensor D identical? True



In [9]:
# Check for GPU access with PyTorch
gpu_available = torch.cuda.is_available()
print(f"Is GPU available? {gpu_available}")

# Count the number of available GPU devices
num_gpus = torch.cuda.device_count()
print(f"Number of GPUs available: {num_gpus}\n")

# Working with tensors on GPU (if available)

# Creating a tensor on CPU
tensor_cpu = torch.tensor([1, 2, 3])
print(f"Tensor on CPU:\n{tensor_cpu}, Device: {tensor_cpu.device}")

# Move tensor to GPU if available
if gpu_available:
    tensor_gpu = tensor_cpu.to(device='cuda')
    print(f"Tensor moved to GPU:\n{tensor_gpu}, Device: {tensor_gpu.device}\n")
else:
    print("No GPU available. Tensor remains on CPU.\n")

# Move tensor back to CPU and convert to NumPy array
tensor_back_to_cpu = tensor_gpu.cpu().numpy() if gpu_available else tensor_cpu.numpy()
print(f"Tensor moved back to CPU and converted to NumPy array:\n{tensor_back_to_cpu}")

Is GPU available? False
Number of GPUs available: 0

Tensor on CPU:
tensor([1, 2, 3]), Device: cpu
No GPU available. Tensor remains on CPU.

Tensor moved back to CPU and converted to NumPy array:
[1 2 3]
